name = "mintdeals2025"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

[env.production]
vars = { BUN_VERSION = "1.1.27" }

[env.preview]
vars = { BUN_VERSION = "1.1.27" }
